const $=i=>document.getElementById(i);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const AFTER={};
const sb=(window.supabase&&CFG.SUPABASE_URL)?supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
const P={};
const cta=(t,s)=>`<section class="alt"><div class="w" style="text-align:center"><h2>${t}</h2><p>${s}</p><a class="btn" href="#/contact">Request a Consultation</a> <a class="btn o" href="#/contact">Contact Our Team</a></div></section>`;
const svc=[["Strategic Planning & Management","Designing and implementing strategies that support organizational growth, innovation and competitiveness.","Organizations needing direction, growth plans or stronger competitiveness.","Examples of formats: strategy sessions, planning workshops, advisory support."],
["Capacity Building","Strengthening the knowledge, skills and institutional capacity needed to achieve objectives and improve performance. Performance reflects capacity, not just opportunity.","Institutions, boards, managers and staff teams.","Examples: leadership and governance training, staff capacity sessions."],
["Change Management","Helping organizations navigate transformation while minimizing disruption and maximizing benefits.","Organizations facing transitions, restructuring or new ways of working.","Examples: transition workshops, retrenchment and retirement preparation sessions."],
["Personal & Talent Development","Equipping individuals and teams with skills, capabilities and personal development tools to improve performance.","Individuals, students, youth and staff teams.","Examples: mentoring programs, youth skills and mindset training."],
["Team Building","Helping teams combine different personalities, strengths and working styles toward a shared purpose.","Teams and departments of any size.","Examples: facilitated team-building exercises and retreats."]];
const spec=["Emotional Intelligence Training","Stress Management","Group Dynamics Facilitation","Business Consultancy","Proposal Development","Problem Solving and Decision Making","Skills Development","Practical Farming Trainings"];
const bsd=[["B","Being","Character · Heart · Spiritual Formation","Develops integrity, personal values, character and a strong internal foundation."],["S","Seeing","Creativity · Mind · Mindset Transformation","Develops new perspectives, creative thinking, self-awareness and the ability to see opportunities differently."],["D","Doing","Competence · Action · Skills Development","Builds practical skills, capabilities and confidence to turn knowledge and ideas into results."]];
const bsdBlock=`<div class="bsd"><svg viewBox="0 0 300 280" role="img" aria-label="BSD Model: Being, Seeing and Doing connected"><path d="M150 50L60 210H240Z" fill="none" stroke="var(--ln)" stroke-width="3"/>
${[[150,50,"B",0],[60,210,"S",1],[240,210,"D",2]].map(([x,y,l,i])=>`<g data-i="${i}" tabindex="0" role="button" aria-label="${bsd[i][1]}"><circle id="c${i}" cx="${x}" cy="${y}" r="42" fill="${i==1?'#37338a':'#2fb361'}"/><text x="${x}" y="${y+12}" text-anchor="middle" font-size="34" font-weight="700" fill="#fff" font-family="Plus Jakarta Sans,Helvetica,sans-serif">${l}</text></g>`).join("")}
<text x="150" y="160" text-anchor="middle" font-size="13" fill="var(--mu)">Uthunthu</text><text x="150" y="176" text-anchor="middle" font-size="13" fill="var(--mu)">completeness</text></svg>
<div><div class="tabs" role="tablist">${bsd.map((b,i)=>`<button role="tab" data-i="${i}" aria-selected="${i==0}">${b[0]} · ${b[1]}</button>`).join("")}</div><div class="panel" id="bp" aria-live="polite"></div></div></div>`;
