// CLIENT LOGOS: files live in images/. To add one, put the file in images/ and add a line: ["file-name-without-.svg","Name"]
const CL=[["worldvision","World Vision"],["global","Global Fund"],["compassion","Compassion Malawi"],["luanar","LUANAR"],["mzuni","MZUNI"],["must","MUST"],["plu","PLU"],["magu","MAGU"],["unima","University of Malawi"],["ccap","CCAP"],["cic","CIC"],["mbs","MBC"],["mibawa","Mibawa"],["zodiac","Zodiak"]];
const logoStrip=()=>{const set=d=>CL.map(c=>`<img${d?' class="d"':''} src="images/${c[0]}.svg" alt="${d?'':c[1]}" loading="lazy" onerror="this.remove()">`).join("");
return `<div class="mq" role="group" aria-label="Organizations we have served"><div class="mt">${set(0)}${set(1)}</div></div>`};
P.home=()=>`<div class="hero"><div class="w"><h1>Building Complete People. Transforming Organizations.</h1><p>Empowering individuals and institutions through character development, mindset transformation and practical skills for sustainable growth.</p><a class="btn g" href="#/services">Explore Our Services</a><a class="btn o" href="#/bsd">Discover the BSD Model</a></div></div>
<section><div class="w"><span class="eyebrow">Since 2014</span><h2>Transformation Begins Within</h2><p style="max-width:760px">Uthunthu Consultancy is a holistic development and transformation firm committed to empowering individuals and organizations to reach their fullest potential. Sustainable progress requires more than technical skills: it also needs strong character, creative thinking, a positive mindset and the ability to turn knowledge into action. Founded in 2014 by Caswel Mkanda, the name comes from the Chichewa word for completeness.</p></div></section>
<section class="alt"><div class="w"><h2>The BSD Model: The Foundation of Transformation</h2>${bsdBlock}<p><a class="btn" href="#/bsd">Explore Our BSD Model</a></p></div></section>
<section><div class="w"><h2>Solutions That Develop People and Strengthen Institutions</h2><div class="grid">${svc.map(s=>`<div class="card"><h3>${s[0]}</h3><p>${s[1].split(". ")[0]}</p><a href="#/services">Learn more</a></div>`).join("")}</div><p><a class="btn" href="#/services">View All Services</a></p></div></section>
<section class="alt"><div class="w"><h2>Developing People Across Different Sectors</h2><div class="grid">${["Universities and higher education","NGOs and development organizations","Churches and faith-based institutions","Corporate and organizational leadership","Youth development and empowerment","Rehabilitation and personal transformation"].map(x=>`<div class="card"><h3>${x}</h3></div>`).join("")}</div><p>Organizations we have served include World Vision International, Global Fund, Compassion Malawi, LUANAR, MZUNI, MUST, MAGU and PLU.</p>${logoStrip()}</div></section>
<section><div class="w"><h2>Why Work With Uthunthu?</h2><div class="grid">${[["Personalized Approach","Programs are tailored to each client's goals, needs and context."],["Expertise and Experience","Experience across different industries, institutions and development settings."],["Collaborative Mindset","We co-create solutions with clients to meet their requirements."],["Measurable Results","A commitment to tangible outcomes and meaningful improvements."]].map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join("")}</div></div></section>
${cta("Let's Build a Culture of Growth and Transformation.","Whether you are developing leaders, strengthening your organization or empowering individuals, Uthunthu Consultancy can help you take the next step.")}`;
